CC=gcc-8.2
CXX=g++-8.2

CFLAGS=-Wall -Wextra -O2 -flto  -std=c99
#CFLAGS=-Wall -Wextra -fsanitize=address -std=c99
LDLIBS=-lm -flto -lstdc++

ALL=bregsplit

all: ${ALL}
clean:
	rm -rf ${ALL} *.o

bregsplit.o: bregsplit.h

bregsplit: 


